### ISSUE TITLE
US1 - Form Page

### ISSUE THREAD

**Issue by alexander-bick** [alexander-bick/capstone-project#1]
## Value Proposition

As a user I want to add new locations to my favourite places app via a form which contains an several input fields to fill the detail cards with content.
​

## Description
<img width="344" alt="FormPage" src="https://github.com/alexander-bick/capstone-project/assets/128151050/f6ca59b7-2fe4-4da2-a9aa-6f780c33e6dc">

​## Acceptance Criteria

- [ ] The heading introduces the upload form page.
- [ ] On the top there is an upload button to add an image.
- [ ] Below are five input fields including "Where", "When", "With me", "Soundtrack" and "Notes".
- [ ] Underneath the input fields there is button to submit the data.
- [ ] The Navbar at the bottom of the page contains four links to the Homepage, the Location List page, the Gallery page and the Form page.

## Tasks

- [ ] write an add form component.
- [ ] add a button to submit an image.
- [ ] create input fields for the data.
- [ ] add a button to submit the data.

      
## Complexity

L

**Comment by Kheirah** [comment]
In case you realize there's too much to be done at once, you can split the story in two and ignore the cloudinary upload for now. In a separate user story you could add it after you're done with the form itself.

**Comment by alexander-bick** [comment]
Thanks for that advice 🙏🏼 Made some changes following it.

**Comment by Charlotte-Ketteler** [comment]
LGTM! Rock'n'Roll! :)
