### ISSUE TITLE
US 6 - Testing

### ISSUE THREAD

**Issue by alexander-bick** [alexander-bick/capstone-project#11]
## Value Proposition

As the developer of the app I want to test a couple of functions inside the components.
​

## Acceptance Criteria

- [ ] Functions like a button or the right display of data will be tested.
      ​

## Tasks

- [ ] Add a index.test.js file to the matching component.
- [ ] Write the tests.
- [ ] Run the tests.
      ​

## Complexity

M

**Comment by Charlotte-Ketteler** [comment]
LGTM! :)
