### ISSUE TITLE
US 7 - Styling

### ISSUE THREAD

**Issue by alexander-bick** [alexander-bick/capstone-project#13]
## Value Proposition

As a user I like to have an easy-to-understand and pleasant UI und UX design.
​

## Description
​
<img width="376" alt="Bildschirmfoto 2023-09-26 um 11 19 46" src="https://github.com/alexander-bick/capstone-project/assets/128151050/c90f610f-c530-43b3-82d5-4fd8f4621eb1">

## Acceptance Criteria

- [ ] The app philosophy is about a very reduced and easily accessible design that leaves no questions to the user.
- [ ] e.g. all inputs are required, show warning if empty.
      ​

## Tasks

- [ ] Change the styling of the List page to have to columns with images.
- [ ] Define the image size on the LocationCard and LocationSuccess page.
- [ ] Fix design issues to have a pleasant experience.
      ​

## Complexity

M
