### ISSUE TITLE
US3 - Add images to location card

### ISSUE THREAD

**Issue by alexander-bick** [alexander-bick/capstone-project#2]
## Value Proposition

As a user I want to add images to the location details cards via a Cloudinary upload form to be able to complete the location details with a visual memory.

## Description

<img width="342" alt="CloudinaryUpload" src="https://github.com/alexander-bick/capstone-project/assets/128151050/afab7a93-f1df-4e11-aa8d-8bc3de01d442">

## Acceptance Criteria

- [ ] By clicking the upload button on the Form page the Cloudinary upload form opens up.
- [ ] The image is shown above the other location details.

## Tasks

- [ ] Create a new branch.
- [ ] Link the Cloudinary form to the image upload button.
- [ ] Store the images at Cloudinary.
- [ ] Write a function to show an image on the location card.
      ​

## Complexity

L
