### ISSUE TITLE
US2 - Location detail card

### ISSUE THREAD

**Issue by alexander-bick** [alexander-bick/capstone-project#3]
## Value Proposition

As a user I want to create a location detail card which shows all the submitted data from the Form page at one glance.

​

## Description

<img width="336" alt="US2_pic" src="https://github.com/alexander-bick/capstone-project/assets/128151050/c9aec51e-4352-4b14-865d-3d0cc28e3f12">

​
## Acceptance Criteria

- [ ] The heading shows the name of the app.
- [ ] The detail card shows an placeholder image on the top for now.
- [ ] Below there are the details shown that have been included via the Form page.
- [ ] They contain the place, the date, possibly companions, a soundtrack and personal notes.

      ​

## Tasks

- [ ] Create a new branch.
- [ ] Create a detail card component.
- [ ] Create a card design including the image and logos for each data category.
- [ ] Write a function to show the data submitted on the Form page next to each logo.
      ​
## Complexity

L

**Comment by Kheirah** [comment]
One side note:
The two buttons, edit and delete, should either be fully implemented or not included at all. If you plan to just put buttons in your app which don't work yet, don't include them. Either fully implement their functionality or don't include them.

**Comment by NicoleHoerner** [comment]
Hi! Where is the picture coming from? Locally stored in project, cloudinary? (as I understand that I can already see the picture?)

**Comment by NicoleHoerner** [comment]
Me again! I saw that you implemented the possibility to upload a picture in your US3! So now it is clear to me! But great for fixing this step here anyway!

**Comment by alexander-bick** [comment]
> Me again! I saw that you implemented the possibility to upload a picture in your US3! So now it is clear to me! But great for fixing this step here anyway!

Thanks for your effort and helpful input! You were absolutely right - the image makes no sense without having knowledge of US3 🙂

**Comment by alexander-bick** [comment]
> One side note: The two buttons, edit and delete, should either be fully implemented or not included at all. If you plan to just put buttons in your app which don't work yet, don't include them. Either fully implement their functionality or don't include them.

Thanks! I will include the buttons in separate US then.
