### ISSUE TITLE
US4 - List of all locations/memories

### ISSUE THREAD

**Issue by alexander-bick** [alexander-bick/capstone-project#7]
## Value Proposition

As a user I want to see a list of all added favourite locations/memories at a glance.
​

## Description

<img width="266" alt="Bildschirmfoto 2023-08-17 um 11 31 54" src="https://github.com/alexander-bick/capstone-project/assets/128151050/484a5900-e508-4ac2-a071-053a4f7b0c74">
​

## Acceptance Criteria

- [ ] The header of the page will show a page title.
- [ ] The list displays all locations/memories that will be confirmed via a button on the LocationCard after submitting the data from the Form Page.
- [ ] Each location/memory in the list will be represented by a thumbnail of the uploaded image.
- [ ] Clicking the thumbnail will open the corresponding LocationCard.
- [ ] The footer with a Navbar will include a link to the Form Page to add a new location/memory at this stage.
      ​

## Tasks

- [ ] Create a new branch.
- [ ] Create a List component.
- [ ] Move the Form from the pages/index.js to a new created pages/form.js.
- [ ] Include a confirmation button to the LocationCard to add the card to the list.
- [ ] Write the code to show the submitted locations/memories in the list component.
- [ ] Instead of the Form move the new List component to the Homepage.
- [ ] Create a header with a page title.
- [ ] Include a footer that contains a Navbar with only a link to the Form Page for now.
      ​

## Complexity

L
