### ISSUE TITLE
US5 - Edit and delete Locations

### ISSUE THREAD

**Issue by alexander-bick** [alexander-bick/capstone-project#9]
## Value Proposition

As a user I want to to be able to edit and delete Locations/Memories.
​

## Description

<img width="347" alt="Bildschirmfoto 2023-09-07 um 10 27 26" src="https://github.com/alexander-bick/capstone-project/assets/128151050/d876d0e6-4ed1-4fbb-b8d4-5af43c80f532">

​

## Acceptance Criteria

- [ ] The LocationCard will show an image and all details submitted before.
- [ ] An edit and a delete button will be implemented below the details.
- [ ] Clicking the edit button will lead to an edit form to change details.
- [ ] Clicking the delete button will delete the LocationCard and also the thumbnail from the List.
- [ ] The footer will contain a return button to route back to the List page.
      ​

## Tasks

- [ ] Create a new branch.
- [ ] Add an edit and a delete button.
- [ ] Implement the function to edit the data of a Location/Memory.
- [ ] Implement the function to delete a Location.
      ​

## Complexity

L

**Comment by Charlotte-Ketteler** [comment]
LGTM :)
